### ISSUE TITLE
Spanish regions that are not countries

### ISSUE THREAD

**Issue by cfaria** [nlemoine/acf-country#21]
Details
-------

 - WordPress version: [ 4.9.8 ]
 - ACF Pro version: [ 5.7.7 ]

### Bug summary

First of all thank you for this great plugin, you've done an incredible work here.

The problem I've found is not yours but umpirsky country list. The problem is that in es_ES (and possibly in all languages) there are some countries that are not countries but Spanish regions, so they are listed in all selects. 

The "countries" that are not countries are (at least the Spanish ones that I've found):
```
'IC' => 'Canarias',
'EA' => 'Ceuta y Melilla',
```

Seems like it should be easier for us to put a filter in the get_countries function in acf-country/fields/acf-country-helpers.php, in order to be able to remove countries from that list, than making a pull request to umpirsky country-list repo removing those wrong countries and wait for you to update the country files...

Would you mind if I make a PR to your repo creating that filter? I don't know if you want to put an specific name to that filter and that's why I didn't do that PR yet.

### Steps to reproduce

In every single select and every single language ;D

**Comment by nlemoine** [comment]
Hi @cfaria 

I just pushed the 2.0 branch: https://github.com/nlemoine/acf-country/tree/2.0

This new major version introduced some important breaking changes (compatibility, data format returned). But the code base is now really lighter and much easier to maintain, the pre-ACF 5.7 versions were a nightmare. Please have a look at the readme file. 

The Umpirsky is not either your issue here. It just grabs all ISO 3166-1 alpha-2 codes and some "regions", even if they belong to a country, have an ISO 3166-1 alpha-2: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations

Anyway, I also added the filter you requested as it might be useful for users. You'll find your example in the readme file. 

Please check and let me know if you encounter any bug. I'll release the 2.0.0 version soon.

**Comment by cfaria** [comment]
That's great @nlemoine. Thank you! 

I'll check it out tomorrow morning and if I find a bug I'll tell you asap.
